Repository wanted-running-sheep/trip, pull requests merged in 2022-08, with the labels that each got.

#8 ✨ feat: data fetching 모듈 추가
  package.json
  server/database/db.json
  server/index.js
  src/api/http/httpRequest.ts
  src/api/instance/index.ts
  src/api/models/useHotelModel.ts
  src/types/enum.ts
Labels: 🕹️ 기능

#14 ✨ feat: 호텔리스트 가져오기 및 무한스크롤
  src/components/HotelCard.tsx
  src/components/HotelList.tsx
  src/components/Spinner.tsx
  src/constants/index.ts
  src/hooks/useFetchHotel.tsx
  src/hooks/useInfiniteScroll.tsx
  src/styles/globalStyles.ts
  src/styles/theme.ts
  src/types/api.d.ts
  src/utils/getFullSearchQuery.ts
  src/utils/getHotelImage.ts
  src/utils/getTotalPage.ts
  src/utils/index.ts
Labels: 🕹️ 기능

#20 ✨ feat: 스켈레톤 UI 구현 및 호텔 목록 스타일 수정
  src/components/HotelCard.tsx
  src/components/HotelList.tsx
  src/components/Skeleton/SkeletonItem.tsx
  src/components/Skeleton/index.tsx
  src/hooks/useFetchHotel.tsx
  src/pages/MainPage.tsx
  src/routes/index.tsx
  src/utils/createArray.ts
Labels: 🕹️ 기능, 📱 UI

#13 ✨ feat: 캘린더 (체크인/체크아웃) 구현
  package-lock.json
  package.json
  src/assets/icons/CalendarIcon.tsx
  src/assets/icons/LeftDirection.tsx
  src/assets/icons/RightDirection.tsx
  src/components/CheckInOutCalendar/Body.tsx
  src/components/CheckInOutCalendar/Calendar.tsx
  src/components/CheckInOutCalendar/Header.tsx
  src/components/CheckInOutCalendar/index.tsx
  src/components/HotelList.tsx
  src/components/Search/index.tsx
  src/components/Skeleton/SkeletonItem.tsx
  src/constants/index.ts
  src/hooks/useCalendar.ts
  src/hooks/useFetchHotel.ts
  src/hooks/useInfiniteScroll.ts
  src/index.tsx
  src/pages/CalendarPage.tsx
  src/pages/index.tsx
  src/recoil/atoms.ts
  src/routes/index.tsx
  src/styles/mixins.ts
  src/styles/theme.ts
  src/types/api.d.ts
  src/types/calendar.ts
  src/types/enum.ts
  src/utils/formatCheckInOutText.ts
  src/utils/formatDateToString.ts
  src/utils/getNights.ts
  src/utils/index.ts
Labels: 🕹️ 기능

#30 💄 style: 모바일 반응형 페이지 - 메인
  package-lock.json
  package.json
  src/components/@common/Spinner.tsx
  src/components/CheckInOutCalendar/Calendar.tsx
  src/components/CheckInOutCalendar/index.tsx
  src/components/Search/GuestCountInput.tsx
  src/components/Search/GuestModal.tsx
  src/components/Search/SearchInput.tsx
  src/components/Search/index.tsx
  src/components/index.ts
  src/styles/media.ts
Labels: 📱 UI

#28 ♻️ refactor: 예약 확인, 삭제
  src/components/ConfirmHotelCard.tsx
  src/components/ConfirmHotelList.tsx
  src/hooks/useFetchResevation.ts
  src/recoil/atoms.ts
  src/recoil/localStorageEffect.ts
  src/types/api.d.ts
Labels: ⬆️ 리팩토링
